version: 2
jobs:
  build:
    environment:
      USER_NAME: rossta
      USER_EMAIL: ross@rossta.net
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.4

    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            gem update --system
            gem install bundler

      - run: ruby --version
      - run: node --version
      - run: bundle --version

      - restore_cache:
          keys:
            - bundle-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - bundle-cache-{{ .Branch }}
            - bundle-cache-

      - run: bundle config set path 'vendor/bundle'
      - run: bundle install

      - save_cache:
          key: bundle-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: npm rebuild node-sass
      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: git config --global -l # debug
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run: bin/rake deploy

workflows:
  version: 2
  deploy-site:
    jobs:
      - build:
          filters:
            branches:
              only: develop
